ekf_node:
  ros__parameters:
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "map"

    # IMU configuration
    imu0: "/imu/data_raw"
    imu0_config: [false, false, false, true, true, false, 
                   false, false, false, false, false, false, 
                   false, false, false, false, false, false]
    imu0_differential: false
    imu0_queue_size: 10

    # Other configurations
    use_control: false
    process_noise_covariance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
