frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true

# IMU0 configuration
imu0: imu/data_raw
imu0_config: [false, false, false, true, true, true, true, false, false, true, false, false, false]
imu0_queue_size: 5
imu0_nodelay: false
imu0_differential: false
imu0_relative: true

# Process noise covariance
process_noise_covariance: [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# IMU covariance
imu0_linear_acceleration_covariance: [0.02, 0, 0,
                                      0, 0.02, 0,
                                      0, 0, 0.02]
imu0_angular_velocity_covariance: [0.02, 0, 0,
                                   0, 0.02, 0,
                                   0, 0, 0.02]

# EKF output topic
publish_tf: true
publish_acceleration: false
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom
